apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: management
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
---
# Headless Service for Infinispan JGroups Node Discovery
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: jgroups
      port: 7800
      targetPort: 7800
      protocol: TCP
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
